name: 'Salesforce SF CLI Action'
author: John Føreland
description: 'This action allows to use Salesforce SF CLI from GitHub Actions'
inputs:
  sfdx-auth-url:
    description: Authorize a Salesforce org using an SFDX auth URL
    required: false
  sf-cli-version:
    description: sf cli version number
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'terminal'  
  color: 'purple'
